# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: "Report a UI bug ğŸ›"
    url: https://github.com/SwissDataScienceCenter/renku-ui/discussions/new?category=bugs
    about: |
      If you have found a bug, please report it in the Discussions section. A maintainer will later create an issue or update existing ones.
  - name: "Suggest new ideas ğŸ’¡"
    url: https://github.com/SwissDataScienceCenter/renku-ui/discussions/new?category=ideas
    about: |
      If you have an idea for a new feature or improvement, please share it in the Discussions section.
  - name: "Renku discussions ğŸ’¬"
    url: https://renku.discourse.group/
    about: |
      Do you have questions about Renku? You can start a discussion in our forum.
