{{ define "deployment-template" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deploymentName }}
  labels:
    app: {{ .appName }}
    chart: {{ template "ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        release: {{ .Release.Name }}
    spec:
      {{- if and .Values.privacy.enabled .Values.privacy.page.enabled }}
      volumes:
        - name: privacy
          configMap:
            name: {{ .Values.privacy.page.configMapName | default (printf "%s-privacy-sample" (include "ui.fullname" .)) | quote }}
            items:
            - key: {{ .Values.privacy.page.configMapKey | default (printf "privacy_statement") | quote }}
              path: statement.md
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .imageName }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if and .Values.privacy.enabled .Values.privacy.page.enabled }}
          volumeMounts:
            - mountPath: /config-privacy
              name: privacy
          {{- end }}
          env:
            - name: BASE_URL
              value: {{ .Values.baseUrl | default (printf "%s://%s" (include "ui.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GATEWAY_URL
              value: {{ .Values.gatewayUrl | default (printf "%s://%s/api" (include "ui.protocol" .) .Values.global.renku.domain) | quote }}
            - name: UISERVER_URL
              value: {{ .Values.uiserverUrl | default (printf "%s://%s/ui-server" (include "ui.protocol" .) .Values.global.renku.domain) | quote }}
            - name: WELCOME_PAGE
              value: {{ .Values.welcomePage.text | b64enc | quote }}
            {{- if .Values.statuspage }}
            - name: STATUSPAGE_ID
              value: {{ .Values.statuspage.id | quote }}
            {{- end }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_URL
              value: {{ .Values.sentry.url | quote }}
            - name: SENTRY_NAMESPACE
              value: {{ .Values.sentry.namespace | default (printf "%s" .Release.Namespace) | quote }}
            - name: SENTRY_SAMPLE_RATE
              value: {{ .Values.sentry.sampleRate | quote }}
            {{- end }}
            {{- if .Values.maintenance }}
            - name: MAINTENANCE
              value: {{ .Values.maintenance | default (printf "false") | quote }}
            {{- end }}
            - name: ANONYMOUS_SESSIONS
              value: {{ .Values.global.anonymousSessions.enabled | default (printf "false") | quote }}
            - name: PRIVACY_ENABLED
              value: {{ .Values.privacy.enabled | quote }}
            {{- if .Values.privacy.enabled }}
            - name: PRIVACY_BANNER_CONTENT
              value: {{ .Values.privacy.banner.content | default (printf "") | b64enc | quote }}
            - name: PRIVACY_BANNER_LAYOUT
              value: {{ toJson .Values.privacy.banner.layout | default (printf "") | quote }}
            {{ else }}
            - name: PRIVACY_BANNER_CONTENT
              value: ""
            - name: PRIVACY_BANNER_LAYOUT
              value: "{}"
            {{- end }}
            - name: TEMPLATES
              value: {{ toJson .Values.templates | quote }}
            - name: PREVIEW_THRESHOLD
              value: {{ toJson .Values.previewSizeThreshold | quote }}
            - name: UPLOAD_THRESHOLD
              value: {{ toJson .Values.uploadSizeThreshold | quote }}
            - name: UI_VERSION
              value: {{ .Chart.Version | quote }}
            - name: HOMEPAGE
              value: {{ toJson .Values.homepage | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
{{- end }}
